-- SELECT F.NOME
-- FROM FORNECEDOR F 
-- WHERE NOT EXISTS (
-- 	SELECT P.*
-- 	FROM PECA P
-- 	WHERE F.COD_FORN = P.COD_FORN 	
-- )

-- SELECT F.NOME, SUM(T.QTD_EST)
-- FROM FORNECEDOR F, PECA T
-- WHERE EXISTS(
-- 	SELECT *
-- 	FROM PECA P
-- 	WHERE F.COD_FORN = P.COD_FORN
-- 	AND P.QTD_EST > 5
-- )
-- AND F.COD_FORN = T.COD_FORN 
-- GROUP BY F.NOME
-- ORDER BY F.NOME

SELECT P.DESCRICAO, F.NOME
FROM PECA P, FORNECEDOR F
WHERE P.COD_FORN IN (3, 4, 5)
AND P.COD_FORN = F.COD_FORN