CREATE TABLE FORNECEDOR (
	COD_FORN SERIAL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	TELEFONE VARCHAR(11) NOT NULL,
	CNPJ VARCHAR(14) NOT NULL UNIQUE
);
CREATE TABLE PECA (
	COD_PECA INT NOT NULL,
	COD_FORN INT NOT NULL REFERENCES FORNECEDOR(COD_FORN),
	DESCRICAO VARCHAR(50),
	TIPO VARCHAR(30) CHECK (TIPO IN ('AUTOMOTIVA', 'MOTO', 'NAUTICA')),
	QTD_EST INT CHECK (QTD_EST >= 0),
	QTD_CAIXA INT CHECK (QTD_CAIXA >= 1),
	PRIMARY KEY(COD_PECA, COD_FORN)
);