CREATE USER FELIPE WITH PASSWORD '1234';
CREATE USER VINI WITH PASSWORD '1234';
CREATE USER SCHEILA WITH PASSWORD '1234';
CREATE USER PAULO WITH PASSWORD '1234';
CREATE USER MARIA WITH PASSWORD '1234';
CREATE USER PATRICIA WITH PASSWORD '1234';
CREATE USER LUIZ WITH PASSWORD '1234';
CREATE USER CLAUDIA WITH PASSWORD '1234';
CREATE USER ROBERTO WITH PASSWORD '1234';

CREATE TABLE CLIENTE(
	COD_CLI SERIAL PRIMARY KEY,
	NOME_CLI VARCHAR(100) NOT NULL
);

CREATE TABLE FINANCEIRO(
	COD SERIAL PRIMARY KEY,
	PAGAMENTO FLOAT NOT NULL,
	COD_CLI INT NOT NULL REFERENCES CLIENTE(COD_CLI)
);

CREATE TABLE CARGO(
	COD_CARGO SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR(50) NOT NULL
);

CREATE TABLE FUNCIONARIO(
	MATRICULA SERIAL PRIMARY KEY,
	NOME_FUNC VARCHAR(100) NOT NULL,
	COD_CARGO INT NOT NULL REFERENCES CARGO(COD_CARGO),
	SALARIO NUMERIC(10, 2) NOT NULL
);

CREATE TABLE PRODUTO(
	COD_PROD SERIAL PRIMARY KEY,
	NOME_PROD VARCHAR(50) NOT NULL,
	PRECO NUMERIC(10, 2) NOT NULL
);

CREATE TABLE VENDA(
	COD_VENDA SERIAL PRIMARY KEY,
	COD_PROD INT NOT NULL REFERENCES PRODUTO(COD_PROD),
	COD_CLI INT NOT NULL REFERENCES CLIENTE(COD_CLI),
	QTD INT NOT NULL,
	DATA_VENDA DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE CHAMADO(
	COD_CHAMADO SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR NOT NULL,
	DATA_CHAMADO DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE ATUALIZACAO_SALARIO(
	COD_LOG SERIAL PRIMARY KEY,
	MATRICULA INT NOT NULL REFERENCES FUNCIONARIO(MATRICULA),
	DATA_ATUALIZACAO TIMESTAMP NOT NULL,
	SAL_ANTERIOR NUMERIC(10, 2) NOT NULL,
	SAL_ATUAL NUMERIC(10, 2) NOT NULL,
	USUARIO VARCHAR(50) NOT NULL	
);