CREATE OR REPLACE FUNCTION ATUALIZA_SALARIO()
RETURNS TRIGGER AS $$
BEGIN
	IF NEW.SALARIO <> OLD.SALARIO THEN
		INSERT INTO ATUALIZACAO_SALARIO(MATRICULA, DATA_ATUALIZACAO, SAL_ANTERIOR, SAL_ATUAL, USUARIO)
		VALUES(NEW.MATRICULA, CURRENT_TIMESTAMP, OLD.SALARIO, NEW.SALARIO, CURRENT_USER);
	END IF;
	RETURN NEW;
END;
$$ LANGUAGE PLPGSQL


CREATE TRIGGER TG_ATUALIZA_SALARIO
AFTER UPDATE 
ON FUNCIONARIO
FOR EACH ROW
EXECUTE PROCEDURE ATUALIZA_SALARIO();

-- Operações feitas com o usuário Patricia

SELECT * FROM FUNCIONARIO

UPDATE FUNCIONARIO
SET SALARIO = 2800
WHERE MATRICULA = 5

SELECT * FROM ATUALIZACAO_SALARIO