-- CREATE ROLE TI;
-- CREATE ROLE ADM;
-- CREATE ROLE RH;
-- CREATE ROLE VENDAS;

-- GRANT TI TO FELIPE;
-- GRANT TI TO VINI;

-- GRANT ADM TO SCHEILA;
-- GRANT ADM TO PAULO;
-- GRANT ADM TO MARIA;

-- GRANT RH TO PATRICIA;

-- GRANT VENDAS TO LUIZ;
-- GRANT VENDAS TO CLAUDIA;
-- GRANT VENDAS TO ROBERTO;

-- GRANT ALL ON ALL TABLES IN SCHEMA PUBLIC TO TI;
-- GRANT ALL ON ALL SEQUENCES IN SCHEMA PUBLIC TO TI;

--Testando se o usuário Felipe consegue relizar crud
-- SELECT * FROM PRODUTO

-- INSERT INTO PRODUTO(NOME_PROD, PRECO)
-- VALUES ('JABINETE', 220.99)

-- UPDATE PRODUTO
-- SET NOME_PROD = 'Gabinete'

-- DELETE FROM PRODUTO 
-- WHERE COD_PROD = 6

-- GRANT SELECT, INSERT, UPDATE ON FINANCEIRO, CLIENTE TO ADM;

-- GRANT ALL ON CARGO, FUNCIONARIO TO RH;
-- GRANT ALL ON ALL SEQUENCES IN SCHEMA PUBLIC TO RH;

-- GRANT SELECT ON CLIENTE TO VENDAS;
-- GRANT SELECT, INSERT, UPDATE ON VENDA TO VENDAS;
-- GRANT ALL ON ALL SEQUENCES IN SCHEMA PUBLIC TO VENDAS;

