CREATE TABLE FORNECEDOR(
	ID_FORNECEDOR SERIAL PRIMARY KEY,
	NOME_FORNECEDOR VARCHAR(100) UNIQUE NOT NULL,
	CIDADE VARCHAR(60) NOT NULL,
	CONTATO VARCHAR(15) NOT NULL
);
CREATE TYPE CATEGORIA_ENUM AS ENUM('INFORMATICA', 'TELEFONIA', 'ENTRETENIMENTO', 'ACESSORIOS');
CREATE TABLE PRODUTO(
	ID_PRODUTO SERIAL PRIMARY KEY,
	NOME_PRODUTO VARCHAR(100) NOT NULL,
	CATEGORIA CATEGORIA_ENUM NOT NULL,
	PRECO FLOAT NOT NULL,
	QTD_EST INT NOT NULL,
	ID_FORNECEDOR INT NOT NULL REFERENCES FORNECEDOR(ID_FORNECEDOR)
);
CREATE TYPE STATUS_ENUM AS ENUM('PENDENTE', 'EM EXECUCAO', 'CONCLUIDA');
CREATE TABLE MANUTENCAO(
	ID_MANUTENCAO SERIAL PRIMARY KEY,
	ID_PRODUTO INT NOT NULL REFERENCES PRODUTO(ID_PRODUTO),
	DATA_SOLICITACAO DATE NOT NULL DEFAULT CURRENT_DATE,
	STATUS STATUS_ENUM NOT NULL
);