CREATE TABLE HOSPEDE(
	COD_HOSP SERIAL PRIMARY KEY,
	NOME_HOSP VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL DEFAULT 'NÃO INFORMADO'
);
CREATE TABLE TELEFONE(
	COD_TEL SERIAL PRIMARY KEY,
	NUM_TEL VARCHAR(11) NOT NULL,
	COD_HOSP INT NOT NULL REFERENCES HOSPEDE(COD_HOSP)
);
CREATE TYPE TQ_ENUM AS ENUM('SINGLE STD', 'SINGLE LUXO', 'CASAL STD', 'CASAL LUXO', 'SUITE MASTER');
CREATE TABLE QUARTO(
	NUM_QUA SERIAL PRIMARY KEY,
	TIPO_QUA TQ_ENUM NOT NULL,
	VALOR_DIARIA FLOAT NOT NULL
);
CREATE TYPE STATUS_ENUM AS ENUM('PENDENTE', 'AGUARDANDO CONFIRMAÇÃO','LIBERADO');
CREATE TABLE RESERVA(
	NUM_RSV SERIAL PRIMARY KEY,
	DT_RSV DATE DEFAULT CURRENT_DATE,
	DT_ENT DATE NOT NULL,
	DT_SAI DATE NOT NULL,
	STATUS STATUS_ENUM NOT NULL,
	COD_HOSP INT REFERENCES HOSPEDE(COD_HOSP),
	NUM_QUA INT REFERENCES QUARTO(NUM_QUA)
);
CREATE TYPE FORMA_ENUM AS ENUM('PIX', 'DINHEIRO', 'DÉBITO', 'CRÉDITO');
CREATE TABLE PAGAMENTO(
	COD_PAG SERIAL PRIMARY KEY,
	FORMA FORMA_ENUM NOT NULL,
	DATA_PAG DATE NOT NULL DEFAULT CURRENT_DATE,
	VALOR_PAG FLOAT NOT NULL,
	NUM_RSV INT REFERENCES RESERVA(NUM_RSV)
);





