-- CREATE TABLE TUTOR(
-- 	COD_TUTOR SERIAL PRIMARY KEY,
-- 	NOME VARCHAR(100) NOT NULL
-- );
-- CREATE TABLE TELEFONE(
-- 	COD_TEL SERIAL PRIMARY KEY,
-- 	NUM_TEL VARCHAR(11) NOT NULL,
-- 	COD_TUTOR INT NOT NULL REFERENCES TUTOR(COD_TUTOR)
-- );
-- CREATE TYPE LOGRA AS ENUM('RUA', 'AVENIDA', 'SERVIDAO', 'MARGINAL', 'TRAVESSA');
-- CREATE TABLE ENDERECO(
-- 	COD_END SERIAL PRIMARY KEY,
-- 	COD_TUTOR INT NOT NULL REFERENCES TUTOR(COD_TUTOR),
-- 	TIPO_LOG LOGRA NOT NULL,
-- 	NUM VARCHAR(20) NOT NULL,
-- 	BAIRRO VARCHAR(100) NOT NULL,
-- 	CIDADE VARCHAR(100) NOT NULL,
-- 	UF VARCHAR(2) NOT NULL DEFAULT 'SC',
-- 	CEP VARCHAR(8)
-- );

-- --ALTER TABLE ENDERECO ADD COLUMN LOGRADOURO VARCHAR(150) NOT NULL;
-- --SELECT * FROM ENDERECO;

-- CREATE TABLE ESPECIE(
-- 	COD_ESP SERIAL PRIMARY KEY,
-- 	NOME_ESP VARCHAR(30) NOT NULL
-- );
-- CREATE TABLE RACA(
-- 	COD_RACA SERIAL PRIMARY KEY,
-- 	NOME_RACA VARCHAR(30),
-- 	COD_ESP INT NOT NULL REFERENCES ESPECIE(COD_ESP)
-- );
-- CREATE TABLE ANIMAL(
-- 	COD_ANIMAL SERIAL PRIMARY KEY,
-- 	NOME VARCHAR(50) NOT NULL,
-- 	COD_RACA INT NOT NULL REFERENCES RACA(COD_RACA),
-- 	DT_NASC DATE,
-- 	PESO FLOAT,
-- 	COD_TUTOR INT NOT NULL REFERENCES TUTOR(COD_TUTOR)
-- );

-- --SELECT * FROM ANIMAL;

-- CREATE TABLE ESPECIALIDADE(
-- 	COD_ESPECIALIDADE SERIAL PRIMARY KEY,
-- 	NOME_ESPECIALIDADE VARCHAR(50) NOT NULL UNIQUE
-- );
-- CREATE SEQUENCE SEQ_VET INCREMENT 10 START 1000;
-- CREATE TABLE VETERINARIO(
-- 	COD_VET INT PRIMARY KEY DEFAULT NEXTVAL('SEQ_VET'),
-- 	NOME VARCHAR(100) NOT NULL,
-- 	REG_PROF VARCHAR(50) NOT NULL,
-- 	COD_ESPECIALIDADE INT REFERENCES ESPECIALIDADE(COD_ESPECIALIDADE)
-- );

-- CREATE TABLE CONSULTA(
-- 	COD_CONSULTA SERIAL PRIMARY KEY,
-- 	DATA_CONSULTA DATE NOT NULL DEFAULT CURRENT_DATE,
-- 	DIAGNOSTICO VARCHAR(200) NOT NULL,
-- 	TRATAMENTE VARCHAR(200) NOT NULL,
-- 	COD_VET INT NOT NULL REFERENCES VETERINARIO(COD_VET),
-- 	COD_ANIMAL INT NOT NULL REFERENCES ANIMAL(COD_ANIMAL)
-- );

--INSERT INTO NOME DA TABELA(COLUNA1, COLUNA2, COLUNAn)
--VALUES(VALUE1, VALUE2, VALUEn)

-- INSERT INTO TUTOR(NOME)
-- VALUES('VITOR BUBOLS'), ('ESTER REGINA'), ('BRUNO PETRI'), ('JANILE OLIVEIRA'), ('RAPHAEL RODRIGUES'),
-- ('AROLDO ARAUJO'), ('PEDRO PAULO'), ('ICE BLUE'), ('KL JAY'), ('MARCELO D2'), ('DAVE MUSTAINE');

-- UPDATE TELEFONE SET NUM_TEL = 4799479625 WHERE COD_TUTOR = 1; 

-- SELECT * FROM TELEFONE WHERE NUM_TEL NOT LIKE ('48%')

SELECT * FROM ENDERECO WHERE CIDADE = ('Florianópolis') ORDER BY BAIRRO


