CREATE TABLE TUTOR(
	COD_TUTOR SERIAL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL
);
CREATE TABLE TELEFONE(
	COD_TEL SERIAL PRIMARY KEY,
	NUM_TEL VARCHAR(11) NOT NULL,
	COD_TUTOR INT NOT NULL REFERENCES TUTOR(COD_TUTOR)
);
CREATE TYPE LOGRA AS ENUM('RUA', 'AVENIDA', 'SERVIDAO', 'MARGINAL', 'TRAVESSA');
CREATE TABLE ENDERECO(
	COD_END SERIAL PRIMARY KEY,
	COD_TUTOR INT NOT NULL REFERENCES TUTOR(COD_TUTOR),
	TIPO_LOG LOGRA NOT NULL,
	NUM VARCHAR(20) NOT NULL,
	BAIRRO VARCHAR(100) NOT NULL,
	CIDADE VARCHAR(100) NOT NULL,
	UF VARCHAR(2) NOT NULL DEFAULT 'SC',
	CEP VARCHAR(8)
);

--ALTER TABLE ENDERECO ADD COLUMN LOGRADOURO VARCHAR(150) NOT NULL;
--SELECT * FROM ENDERECO;

CREATE TABLE ESPECIE(
	COD_ESP SERIAL PRIMARY KEY,
	NOME_ESP VARCHAR(30) NOT NULL
);
CREATE TABLE RACA(
	COD_RACA SERIAL PRIMARY KEY,
	NOME_RACA VARCHAR(30),
	COD_ESP INT NOT NULL REFERENCES ESPECIE(COD_ESP)
);
CREATE TABLE ANIMAL(
	COD_ANIMAL SERIAL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	COD_RACA INT NOT NULL REFERENCES RACA(COD_RACA),
	DT_NASC DATE,
	PESO FLOAT,
	COD_TUTOR INT NOT NULL REFERENCES TUTOR(COD_TUTOR)
);

--SELECT * FROM ANIMAL;