CREATE OR REPLACE FUNCTION EXIBE_MSG()
RETURNS VARCHAR AS 
$$
DECLARE MSG VARCHAR;
BEGIN
	MSG = 'SALVE';
	RETURN MSG;
END;
$$
LANGUAGE PLPGSQL;

SELECT EXIBE_MSG();

CREATE OR REPLACE FUNCTION SOMA_NUMS2(N1 INT, N2 INT)
RETURNS TEXT AS 
$$
BEGIN
	RETURN 'A soma dos números é: ' || N1 + N2;
END;
$$
LANGUAGE PLPGSQL;

SELECT SOMA_NUMS2(675, 2313);

CREATE OR REPLACE FUNCTION FORMATA_MOEDA(VAL FLOAT)
RETURNS VARCHAR AS
$$
BEGIN
	RETURN 'R$' || ROUND(CAST(VAL AS NUMERIC), 2);
END;
$$
LANGUAGE PLPGSQL;

SELECT NOME_PRODUTO, FORMATA_MOEDA(VALOR_UNITARIO) AS VALOR_UNITARIO FROM PRODUTO


CREATE OR REPLACE FUNCTION CLASSIFICA_PROD(VAL DOUBLE PRECISION)
RETURNS TEXT AS $$
BEGIN
	IF VAL < 120 THEN 
		RETURN 'BARATO';
	ELSIF VAL < 500 THEN
		RETURN 'INTERMEDIARIO';
	ELSE
		RETURN 'CARO';
	END IF;
END;
$$ LANGUAGE PLPGSQL;

SELECT 
NOME_PRODUTO,
FORMATA_MOEDA(VALOR_UNITARIO) AS PRECO,
CLASSIFICA_PROD(VALOR_UNITARIO) AS TIPO
FROM PRODUTO

CREATE OR REPLACE FUNCTION INSERE_PROD(NOME VARCHAR(50), VALOR NUMERIC(10,2))
RETURNS VARCHAR AS $$
BEGIN
	INSERT INTO PRODUTO(NOME_PRODUTO, VALOR_UNITARIO)
	VALUES (NOME, VALOR);
	RETURN CONCAT('REGISTRO SALVO COM SUCESSO: ', NOME, ' - R$', VALOR);
END;
$$ LANGUAGE PLPGSQL;

SELECT INSERE_PROD('RTX 4070', 2500);
SELECT * FROM PRODUTO;

SELECT * FROM ITEM_PEDIDO

CREATE VIEW TOTAL2 AS 
SELECT P.VALOR_UNITARIO, I.QUANTIDADE, P.NOME_PRODUTO
FROM PRODUTO P, ITEM_PEDIDO I
WHERE P.IDPRODUTO = I.IDPRODUTO;

SELECT * FROM TOTAL2

CREATE OR REPLACE FUNCTION CALC_TOTAL(VALOR FLOAT, QTD INT)
RETURNS FLOAT AS $$
BEGIN
	RETURN SUM(VALOR * QTD);
END;
$$ LANGUAGE PLPGSQL;

SELECT NOME_PRODUTO, VALOR_UNITARIO AS PRECO, QUANTIDADE, CALC_TOTAL(VALOR_UNITARIO, QUANTIDADE)
FROM TOTAL2
ORDER BY QUANTIDADE DESC