CREATE ROLE GRUPO_RH;
CREATE ROLE GRUPO_GERENTE;
CREATE ROLE GRUPO_ESTAGIARIO;

CREATE USER MARIA WITH PASSWORD '1234';
CREATE USER JOAO WITH PASSWORD '1234';
CREATE USER PEDRO WITH PASSWORD '1234';
CREATE USER ANA WITH PASSWORD '1234';
CREATE USER PAULO WITH PASSWORD '1234';
CREATE USER HELENA WITH PASSWORD '1234';

GRANT GRUPO_RH TO MARIA, JOAO;
GRANT GRUPO_GERENTE TO PEDRO, ANA;
GRANT GRUPO_ESTAGIARIO TO PAULO, HELENA;

ALTER ROLE grupo_rh INHERIT;
ALTER ROLE grupo_gerente INHERIT;
ALTER ROLE grupo_estagiario INHERIT;
