CREATE TYPE STATUS_ENUM AS ENUM('DISPONIVEL', 'EM MANUTENCAO', 'FORA DE OPERACAO');
CREATE TABLE VEICULO(
	COD_VEI SERIAL PRIMARY KEY,
	PLACA VARCHAR(7) UNIQUE NOT NULL,
	MODELO VARCHAR(20) NOT NULL,
	ANO VARCHAR(4) NOT NULL,
	KM INT NOT NULL,
	STATUS STATUS_ENUM NOT NULL
);
CREATE TABLE MOTORISTA(
	COD_MOT SERIAL PRIMARY KEY,
	NOME VARCHAR(20) NOT NULL,
	CNH VARCHAR(20) UNIQUE NOT NULL,
	CIDADE_ORG VARCHAR(20) NOT NULL
);
CREATE TABLE TELEFONE(
	COD_TEL SERIAL PRIMARY KEY,
	NUM_TEL VARCHAR(11) NOT NULL,
	COD_MOT INT NOT NULL REFERENCES MOTORISTA(COD_MOT)
);
CREATE TABLE VIAGEM(
	COD_VIA SERIAL PRIMARY KEY,
	COD_MOT INT NOT NULL REFERENCES MOTORISTA(COD_MOT),
	COD_VEI INT NOT NULL REFERENCES VEICULO(COD_VEI),
	DATA_SAI DATE NOT NULL,
	DESTINO VARCHAR(20) NOT NULL,
	DISTANCIA INT NOT NULL
);
CREATE TYPE TIPO_OCR_ENUM AS ENUM('ACIDENTE', 'MANUTENCAO', 'ATRASO');
CREATE TABLE OCORRENCIA(
	COD_OCR SERIAL PRIMARY KEY,
	COD_VIA INT NOT NULL REFERENCES VIAGEM(COD_VIA),
	DATA_OCR DATE NOT NULL,
	TIPO_OCR TIPO_OCR_ENUM NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL
);